redhat: adjust IP bonding to bond0 only
packethost/packet-networking pull request #58
Opened 2022-08-11 15:40 UTC by dustinmiller

It's possible that adding IPs to bond1 can create a scenario where 
networking isn't happy. Lets remove those accordingly

2022-08-18 15:42 UTC, nuclearbob requested changes
bond isn't a variable in the jinja environment, it gets replaced in a formatting pass before the template is rendered. These changes allowed the tests to pass locally for me.

2022-08-18 15:42 UTC, nuclearbob commented on packetnetworking/distros/redhat/templates/bonded/etc_sysconfig_network-scripts_ifcfg-bondX.j2
> +{{% if bond == "bond0" %}}
```suggestion
{{% if "{bond}" == "bond0" %}}
```

2022-08-18 15:42 UTC, nuclearbob commented on packetnetworking/distros/redhat/templates/bonded/etc_sysconfig_network-scripts_ifcfg-bondX.j2
> +{{% if bond == "bond0" %}}
```suggestion
{{% if "{bond}" == "bond0" %}}
```

2022-08-22 15:59 UTC, nuclearbob approved these changes
Ship it!

2022-08-26 15:48 UTC, mikemrm requested changes
Other than this, and testing changes. looks good

2022-08-26 15:48 UTC, mikemrm commented on packetnetworking/distros/redhat/templates/bonded/etc_sysconfig_network-scripts_ifcfg-bondX.j2
> +{{% if "{bond}" == "bond0" %}}
```suggestion
{{% if bond == "bond0" %}}
```

2022-08-26 15:54 UTC, mikemrm commented on packetnetworking/distros/redhat/templates/bonded/etc_sysconfig_network-scripts_ifcfg-bondX.j2
> +{{% if "{bond}" == "bond0" %}}
🤦 this is python formatted before it's handled with jinja2, so this is proper

2022-08-26 15:55 UTC, mikemrm approved these changes
once live tests have been completed, 👍

2022-08-30 14:57 UTC, nuclearbob commented
Testing on actual machines went well except for n3.xlarge.x86, which shows problems on alma_8, rocky_8, and centos_8. alma and rocky install correctly with current osie, so I'm looking into what goes wrong when we use the new one.

2022-09-01 15:20 UTC, nuclearbob commented
alma_8 is now broken with or without this, so let's go ahead and land it, and I'll keep working on alma.

2022-09-01 15:21 UTC, nuclearbob commented
Oh, let's get a review from another team? Maybe @nshalman can recommend someone?

2022-09-06 20:41 UTC, nuclearbob commented
Do we still want a review from another team on this, or is it okay to go in since it's a fix requested by another team and it's pretty small? Either way, I'd like to keep moving on this since it fixes issues in some of the plans we're enabling.

2022-09-13 18:34 UTC, merged